export const investorsListData = {
  1: [
    {
      name: "마스터",
      amount: "999억",
      rank: 1,
      comment: "최고의 투자자입니다.",
      password: "1234",
    },
    {
      name: "김지훈",
      amount: "100억",
      rank: 2,
      comment: "코드잇의 미래 성장성이 기대됩니다.",
      password: "1736",
    },
    {
      name: "이서연",
      amount: "98억",
      rank: 3,
      comment: "콘텐츠 퀄리티가 매우 뛰어납니다.",
      password: "2381",
    },
    {
      name: "박민수",
      amount: "96억",
      rank: 4,
      comment: "시장 선도 기업으로 계속 성장하길 바랍니다.",
      password: "5904",
    },
    {
      name: "최윤아",
      amount: "94억",
      rank: 5,
      comment: "젊고 혁신적인 팀이 인상적입니다.",
      password: "4112",
    },
    {
      name: "정현우",
      amount: "92억",
      rank: 6,
      comment: "꾸준한 기술 개발이 강점입니다.",
      password: "8362",
    },
    {
      name: "오지은",
      amount: "90억",
      rank: 7,
      comment: "업계 리더십을 계속 유지하길 바랍니다.",
      password: "9443",
    },
    {
      name: "배준호",
      amount: "88억",
      rank: 8,
      comment: "에듀테크 트렌드를 선도하고 있습니다.",
      password: "2901",
    },
    {
      name: "장예린",
      amount: "86억",
      rank: 9,
      comment: "팀 분위기가 매우 좋아 보입니다.",
      password: "4175",
    },
    {
      name: "임태환",
      amount: "84억",
      rank: 10,
      comment: "사업 확장성이 매우 높다고 생각합니다.",
      password: "6750",
    },
    {
      name: "윤다혜",
      amount: "82억",
      rank: 11,
      comment: "지속적인 성장세가 인상적입니다.",
      password: "3035",
    },
    {
      name: "신예찬",
      amount: "80억",
      rank: 12,
      comment: "투명한 경영이 돋보입니다.",
      password: "1267",
    },
    {
      name: "서가은",
      amount: "78억",
      rank: 13,
      comment: "교육 시장에서 큰 역할을 하고 있습니다.",
      password: "6219",
    },
    {
      name: "이민지",
      amount: "76억",
      rank: 14,
      comment: "탄탄한 개발진을 보유하고 있어 믿음이 갑니다.",
      password: "9840",
    },
    {
      name: "황수현",
      amount: "74억",
      rank: 15,
      comment: "혁신적인 서비스에 투자를 결정했습니다.",
      password: "2208",
    },
    {
      name: "고현정",
      amount: "72억",
      rank: 16,
      comment: "장기적으로 기대되는 기업입니다.",
      password: "7773",
    },
    {
      name: "문동현",
      amount: "70억",
      rank: 17,
      comment: "서비스 품질이 최고 수준입니다.",
      password: "5954",
    },
    {
      name: "유지훈",
      amount: "68억",
      rank: 18,
      comment: "고객 만족도가 높아 인상적입니다.",
      password: "3140",
    },
    {
      name: "송유진",
      amount: "66억",
      rank: 19,
      comment: "앞으로의 행보가 기대됩니다.",
      password: "4765",
    },
    {
      name: "안다영",
      amount: "64억",
      rank: 20,
      comment: "교육 혁신의 대표 기업이라 생각합니다.",
      password: "1880",
    },
    {
      name: "정수빈",
      amount: "62억",
      rank: 21,
      comment: "빠른 성장 속도가 놀랍습니다.",
      password: "8805",
    },
    {
      name: "하도윤",
      amount: "60억",
      rank: 22,
      comment: "긍정적인 조직 문화가 매력적입니다.",
      password: "5291",
    },
    {
      name: "조은우",
      amount: "58억",
      rank: 23,
      comment: "우수한 리더십에 신뢰가 갑니다.",
      password: "9904",
    },
    {
      name: "차승민",
      amount: "56억",
      rank: 24,
      comment: "기술력과 시장성이 모두 뛰어납니다.",
      password: "1410",
    },
    {
      name: "백현지",
      amount: "54억",
      rank: 25,
      comment: "업계의 혁신을 이끌고 있습니다.",
      password: "6164",
    },
    {
      name: "송진호",
      amount: "52억",
      rank: 26,
      comment: "지속적인 연구개발을 응원합니다.",
      password: "4783",
    },
    {
      name: "임하늘",
      amount: "50억",
      rank: 27,
      comment: "강한 추진력이 인상적입니다.",
      password: "3261",
    },
    {
      name: "김나연",
      amount: "48억",
      rank: 28,
      comment: "성장 동력이 충분합니다.",
      password: "5227",
    },
    {
      name: "이승주",
      amount: "46억",
      rank: 29,
      comment: "혁신적 아이디어가 많아 기대가 큽니다.",
      password: "2752",
    },
    {
      name: "정다인",
      amount: "44억",
      rank: 30,
      comment: "업계의 변화에 앞장서고 있습니다.",
      password: "8489",
    },
    {
      name: "박정우",
      amount: "42억",
      rank: 31,
      comment: "경영진의 결단력이 돋보입니다.",
      password: "9612",
    },
    {
      name: "최가람",
      amount: "40억",
      rank: 32,
      comment: "사회적 가치 창출에도 힘쓰고 있습니다.",
      password: "3577",
    },
    {
      name: "이주연",
      amount: "38억",
      rank: 33,
      comment: "고객 중심 서비스가 인상적입니다.",
      password: "7751",
    },
    {
      name: "유지아",
      amount: "36억",
      rank: 34,
      comment: "기업 가치가 점점 상승하고 있습니다.",
      password: "1120",
    },
    {
      name: "노지훈",
      amount: "34억",
      rank: 35,
      comment: "데이터 기반 의사결정이 강점입니다.",
      password: "4628",
    },
    {
      name: "남승연",
      amount: "32억",
      rank: 36,
      comment: "전문성 높은 인재들이 모였습니다.",
      password: "9905",
    },
    {
      name: "홍승우",
      amount: "30억",
      rank: 37,
      comment: "책임감 있는 경영이 돋보입니다.",
      password: "8421",
    },
    {
      name: "강지수",
      amount: "28억",
      rank: 38,
      comment: "미래지향적 비전을 높이 평가합니다.",
      password: "4912",
    },
    {
      name: "백지훈",
      amount: "26억",
      rank: 39,
      comment: "투자 가치가 높아 보입니다.",
      password: "7812",
    },
    {
      name: "안서현",
      amount: "24억",
      rank: 40,
      comment: "끊임없는 도전정신이 멋집니다.",
      password: "1364",
    },
    {
      name: "신동현",
      amount: "22억",
      rank: 41,
      comment: "더욱 성장하는 코드잇을 응원합니다.",
      password: "0917",
    },
  ],
  2: [
    {
      name: "마스터",
      amount: "999억",
      rank: 1,
      comment: "최고의 투자자입니다.",
      password: "1234",
    },
    {
      name: "박지훈",
      amount: "120억",
      rank: 2,
      comment: "팀스파르타의 혁신적인 교육 방식에 감탄했습니다.",
      password: "5678",
    },
    {
      name: "김민준",
      amount: "117억",
      rank: 3,
      comment: "수강생 만족도가 업계 최고입니다.",
      password: "0012",
    },
    {
      name: "이예린",
      amount: "114억",
      rank: 4,
      comment: "체계적인 부트캠프 운영이 강점입니다.",
      password: "4422",
    },
    {
      name: "조은별",
      amount: "111억",
      rank: 5,
      comment: "기술 교육에 대한 깊은 이해가 느껴집니다.",
      password: "2267",
    },
    {
      name: "홍세진",
      amount: "108억",
      rank: 6,
      comment: "교육 콘텐츠가 다양하고 깊이 있습니다.",
      password: "9915",
    },
    {
      name: "서진혁",
      amount: "105억",
      rank: 7,
      comment: "실무에 바로 적용 가능한 커리큘럼이 인상적입니다.",
      password: "5118",
    },
    {
      name: "차민서",
      amount: "102억",
      rank: 8,
      comment: "교육 시장 트렌드에 항상 앞서 있습니다.",
      password: "7379",
    },
    {
      name: "강지민",
      amount: "99억",
      rank: 9,
      comment: "실무 역량 향상에 최고의 선택입니다.",
      password: "1890",
    },
    {
      name: "문지우",
      amount: "96억",
      rank: 10,
      comment: "참여자 성장에 힘을 실어주는 기업입니다.",
      password: "5432",
    },
    {
      name: "백승아",
      amount: "93억",
      rank: 11,
      comment: "기업 문화가 매우 건강합니다.",
      password: "7418",
    },
    {
      name: "윤지호",
      amount: "90억",
      rank: 12,
      comment: "끊임없는 개선과 혁신에 주목합니다.",
      password: "3178",
    },
    {
      name: "최재원",
      amount: "87억",
      rank: 13,
      comment: "디테일한 관리가 신뢰를 줍니다.",
      password: "8811",
    },
    {
      name: "송다은",
      amount: "84억",
      rank: 14,
      comment: "개발자 양성에 앞장서고 있습니다.",
      password: "6789",
    },
    {
      name: "남도현",
      amount: "81억",
      rank: 15,
      comment: "참여자 피드백 반영이 매우 빠릅니다.",
      password: "1163",
    },
    {
      name: "임세진",
      amount: "78억",
      rank: 16,
      comment: "열정 가득한 조직이 인상적입니다.",
      password: "4391",
    },
    {
      name: "노승현",
      amount: "75억",
      rank: 17,
      comment: "지속 가능한 성장 전략을 기대합니다.",
      password: "2207",
    },
    {
      name: "하예진",
      amount: "72억",
      rank: 18,
      comment: "빠른 시장 대응력이 뛰어납니다.",
      password: "7528",
    },
    {
      name: "정승우",
      amount: "69억",
      rank: 19,
      comment: "교육 환경이 매우 우수합니다.",
      password: "3881",
    },
    {
      name: "이강민",
      amount: "66억",
      rank: 20,
      comment: "기업의 비전이 명확합니다.",
      password: "9231",
    },
    {
      name: "권하윤",
      amount: "63억",
      rank: 21,
      comment: "우수한 인재 확보에 성공했습니다.",
      password: "1715",
    },
    {
      name: "김도윤",
      amount: "60억",
      rank: 22,
      comment: "혁신적 커리큘럼에 높은 점수 줍니다.",
      password: "2139",
    },
    {
      name: "오준서",
      amount: "57억",
      rank: 23,
      comment: "투자 가치가 매우 높습니다.",
      password: "5761",
    },
    {
      name: "이정민",
      amount: "54억",
      rank: 24,
      comment: "미래 교육 패러다임을 바꾸는 기업입니다.",
      password: "5521",
    },
    {
      name: "정다온",
      amount: "51억",
      rank: 25,
      comment: "경영진의 전문성이 인상적입니다.",
      password: "8385",
    },
    {
      name: "박유진",
      amount: "48억",
      rank: 26,
      comment: "데이터 기반 의사결정이 강점입니다.",
      password: "9071",
    },
    {
      name: "강예린",
      amount: "45억",
      rank: 27,
      comment: "글로벌 시장에서도 통할 기업입니다.",
      password: "6205",
    },
    {
      name: "서민재",
      amount: "42억",
      rank: 28,
      comment: "신뢰할 수 있는 경영을 보여줍니다.",
      password: "1663",
    },
    {
      name: "임소율",
      amount: "39억",
      rank: 29,
      comment: "업계 표준이 될 것이라 믿습니다.",
      password: "7382",
    },
    {
      name: "최지우",
      amount: "36억",
      rank: 30,
      comment: "창의적 아이디어가 넘치는 기업입니다.",
      password: "4302",
    },
    {
      name: "남지훈",
      amount: "33억",
      rank: 31,
      comment: "기업의 가치가 계속 상승하고 있습니다.",
      password: "8215",
    },
    {
      name: "이은채",
      amount: "30억",
      rank: 32,
      comment: "미래가 기대되는 성장주입니다.",
      password: "5507",
    },
    {
      name: "홍도윤",
      amount: "27억",
      rank: 33,
      comment: "교육 분야 최고 기업으로 성장하길 바랍니다.",
      password: "2292",
    },
    {
      name: "김태호",
      amount: "24억",
      rank: 34,
      comment: "참신한 서비스가 매력적입니다.",
      password: "1774",
    },
    {
      name: "안지후",
      amount: "21억",
      rank: 35,
      comment: "탄탄한 파트너십이 돋보입니다.",
      password: "9920",
    },
    {
      name: "유하늘",
      amount: "18억",
      rank: 36,
      comment: "사회적 책임을 다하는 기업이라 생각합니다.",
      password: "6702",
    },
    {
      name: "송하윤",
      amount: "15억",
      rank: 37,
      comment: "혁신적이고 창의적인 기업입니다.",
      password: "2191",
    },
    {
      name: "임도현",
      amount: "12억",
      rank: 38,
      comment: "최고의 강사진을 확보했습니다.",
      password: "1255",
    },
    {
      name: "배하린",
      amount: "9억",
      rank: 39,
      comment: "산업 내 입지가 탄탄합니다.",
      password: "5338",
    },
    {
      name: "이서준",
      amount: "6억",
      rank: 40,
      comment: "팀의 전문성이 매우 뛰어납니다.",
      password: "3344",
    },
    {
      name: "전수진",
      amount: "3억",
      rank: 41,
      comment: "팀스파르타의 미래를 응원합니다.",
      password: "8888",
    },
  ],
  3: [
    {
      name: "마스터",
      amount: "999억",
      rank: 1,
      comment: "최고의 투자자입니다.",
      password: "1234",
    },
    {
      name: "정지호",
      amount: "80억",
      rank: 2,
      comment: "인프랩의 IT 플랫폼 성장세가 매우 인상적입니다.",
      password: "2024",
    },
    {
      name: "이도현",
      amount: "78억",
      rank: 3,
      comment: "업계 트렌드를 잘 반영하고 있습니다.",
      password: "7811",
    },
    {
      name: "김채원",
      amount: "76억",
      rank: 4,
      comment: "꾸준한 신규 서비스 런칭이 돋보입니다.",
      password: "5219",
    },
    {
      name: "박나은",
      amount: "74억",
      rank: 5,
      comment: "기술력과 시장 이해도가 높습니다.",
      password: "6642",
    },
    {
      name: "손민재",
      amount: "72억",
      rank: 6,
      comment: "빠른 피드백과 개선이 강점입니다.",
      password: "9227",
    },
    {
      name: "윤예린",
      amount: "70억",
      rank: 7,
      comment: "회원 관리 시스템이 체계적입니다.",
      password: "3117",
    },
    {
      name: "홍지민",
      amount: "68억",
      rank: 8,
      comment: "창의적인 아이디어에 박수를 보냅니다.",
      password: "7754",
    },
    {
      name: "노유진",
      amount: "66억",
      rank: 9,
      comment: "미래 성장성이 뛰어납니다.",
      password: "8172",
    },
    {
      name: "강승민",
      amount: "64억",
      rank: 10,
      comment: "교육 업계의 새로운 표준을 만듭니다.",
      password: "4102",
    },
    {
      name: "하예린",
      amount: "62억",
      rank: 11,
      comment: "팀워크와 기업 문화가 매우 좋습니다.",
      password: "2136",
    },
    {
      name: "이은호",
      amount: "60억",
      rank: 12,
      comment: "기술 기반 서비스가 인상적입니다.",
      password: "5889",
    },
    {
      name: "김다온",
      amount: "58억",
      rank: 13,
      comment: "확실한 비즈니스 모델을 갖고 있습니다.",
      password: "9510",
    },
    {
      name: "이재윤",
      amount: "56억",
      rank: 14,
      comment: "신규 유저 유입이 계속되고 있습니다.",
      password: "1477",
    },
    {
      name: "오유진",
      amount: "54억",
      rank: 15,
      comment: "업계 내 평판이 매우 좋습니다.",
      password: "3973",
    },
    {
      name: "윤성우",
      amount: "52억",
      rank: 16,
      comment: "인재 관리가 잘 이루어지고 있습니다.",
      password: "3917",
    },
    {
      name: "배지민",
      amount: "50억",
      rank: 17,
      comment: "회원수 증가가 기대됩니다.",
      password: "5150",
    },
    {
      name: "송하람",
      amount: "48억",
      rank: 18,
      comment: "경영진의 전략이 탁월합니다.",
      password: "2861",
    },
    {
      name: "임하윤",
      amount: "46억",
      rank: 19,
      comment: "효율적인 운영 시스템이 인상적입니다.",
      password: "9335",
    },
    {
      name: "권도윤",
      amount: "44억",
      rank: 20,
      comment: "마케팅 전략이 독특합니다.",
      password: "6442",
    },
    {
      name: "김예린",
      amount: "42억",
      rank: 21,
      comment: "고객 관리 서비스가 우수합니다.",
      password: "8857",
    },
    {
      name: "이승훈",
      amount: "40억",
      rank: 22,
      comment: "회원들의 만족도가 매우 높습니다.",
      password: "7728",
    },
    {
      name: "정지윤",
      amount: "38억",
      rank: 23,
      comment: "끊임없이 발전하는 모습이 인상적입니다.",
      password: "3012",
    },
    {
      name: "강태현",
      amount: "36억",
      rank: 24,
      comment: "서비스 품질 관리가 잘 이루어지고 있습니다.",
      password: "5769",
    },
    {
      name: "송윤아",
      amount: "34억",
      rank: 25,
      comment: "기업의 신뢰도가 높습니다.",
      password: "1094",
    },
    {
      name: "임지현",
      amount: "32억",
      rank: 26,
      comment: "사용자 친화적 인터페이스가 좋습니다.",
      password: "2078",
    },
    {
      name: "오예준",
      amount: "30억",
      rank: 27,
      comment: "앞으로의 발전이 더욱 기대됩니다.",
      password: "3851",
    },
    {
      name: "윤나현",
      amount: "28억",
      rank: 28,
      comment: "신규 서비스가 계속 나와서 좋습니다.",
      password: "4772",
    },
    {
      name: "김진아",
      amount: "26억",
      rank: 29,
      comment: "회원과 강사 모두를 생각하는 기업입니다.",
      password: "1813",
    },
    {
      name: "박수진",
      amount: "24억",
      rank: 30,
      comment: "기술 발전에 대한 투자가 돋보입니다.",
      password: "4538",
    },
    {
      name: "하진우",
      amount: "22억",
      rank: 31,
      comment: "미래 IT 인재 양성에 기대가 큽니다.",
      password: "5261",
    },
    {
      name: "서예림",
      amount: "20억",
      rank: 32,
      comment: "업계에서 경쟁력이 확실합니다.",
      password: "1542",
    },
    {
      name: "노가은",
      amount: "18억",
      rank: 33,
      comment: "서비스의 지속성장 가능성이 높습니다.",
      password: "2824",
    },
    {
      name: "정혜원",
      amount: "16억",
      rank: 34,
      comment: "믿음직한 기업 경영이 보입니다.",
      password: "2096",
    },
    {
      name: "남도현",
      amount: "14억",
      rank: 35,
      comment: "꾸준한 서비스 개선에 높은 점수를 줍니다",
      password: "3459",
    },
  ],
};
