export const invInitialData = [
  /****************
   * id - 기업 id
   * description - 기업소개
   * category - 카테고리
   * totalInvestment - 누적투자금액
   * revenue - 매출액
   * employees - 고용인원
   * investmentStage - 투자단계 (안쓰임)
   * investors - 투자기관 (아직안쓰임)
   * userInvestment - 이 기업에 투자한 유저id (임시)
   * myCompanySelectedCount - 내기업선택횟수
   * vmsInvestment - ViewMyStartup 에서 투자한 금액
   * compareSelectedCount - 비교기업선택횟수
   ****************/
  {
    "id": 1,
    "companyName": "팀스파르타 1",
    "description": "빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다. 이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "154억",
    "revenue": "653.5억",
    "employees": "410명",
    "investmentStage": "비공개",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId1",
    "myCompanySelectedCount": 43150,
    "vmsInvestment": "168억",
    "compareSelectedCount": 35002
  },
  {
    "id": 2,
    "companyName": "클래스101 2",
    "description": "이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다. 빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "323억",
    "revenue": "522.6억",
    "employees": "84명",
    "investmentStage": "프리시리즈B",
    "investors": "스마일게이트인베스트먼트,해시드,와이콤비네이터",
    "userInvestment": "userId2",
    "myCompanySelectedCount": 54787,
    "vmsInvestment": "112억",
    "compareSelectedCount": 22218
  },
  {
    "id": 3,
    "companyName": "코드스테이츠 3",
    "description": "사용자의 편의성을 고려한 직관적인 UX/UI를 제공합니다. 빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다. 기술력과 창의성을 기반으로 차별화된 서비스를 운영하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "270억",
    "revenue": "549.3억",
    "employees": "229명",
    "investmentStage": "시리즈B",
    "investors": "스마일게이트인베스트먼트,해시드,와이콤비네이터",
    "userInvestment": "userId3",
    "myCompanySelectedCount": 28229,
    "vmsInvestment": "81억",
    "compareSelectedCount": 15711
  },
  {
    "id": 4,
    "companyName": "코드스테이츠 4",
    "description": "국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다. 사용자의 편의성을 고려한 직관적인 UX/UI를 제공합니다. 기술력과 창의성을 기반으로 차별화된 서비스를 운영하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "649억",
    "revenue": "646.7억",
    "employees": "161명",
    "investmentStage": "프리시리즈B",
    "investors": "스마일게이트인베스트먼트,해시드,와이콤비네이터",
    "userInvestment": "userId4",
    "myCompanySelectedCount": 10192,
    "vmsInvestment": "194억",
    "compareSelectedCount": 3210
  },
  {
    "id": 5,
    "companyName": "코멘토 5",
    "description": "사용자의 편의성을 고려한 직관적인 UX/UI를 제공합니다. 국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다. 기술력과 창의성을 기반으로 차별화된 서비스를 운영하고 있습니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "127억",
    "revenue": "590.8억",
    "employees": "509명",
    "investmentStage": "프리시리즈A",
    "investors": "캡스톤파트너스,케이비인베스트먼트,디쓰리쥬빌리파트너스",
    "userInvestment": "userId5",
    "myCompanySelectedCount": 16036,
    "vmsInvestment": "152억",
    "compareSelectedCount": 35012
  },
  {
    "id": 6,
    "companyName": "메이저맵 6",
    "description": "지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "465억",
    "revenue": "628.7억",
    "employees": "354명",
    "investmentStage": "시드투자",
    "investors": "스마일게이트인베스트먼트,해시드,와이콤비네이터",
    "userInvestment": "userId6",
    "myCompanySelectedCount": 2646,
    "vmsInvestment": "21억",
    "compareSelectedCount": 34146
  },
  {
    "id": 7,
    "companyName": "로앤컴퍼니 7",
    "description": "지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다. 국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "796억",
    "revenue": "108.9억",
    "employees": "419명",
    "investmentStage": "프리시리즈A",
    "investors": "캡스톤파트너스,케이비인베스트먼트,디쓰리쥬빌리파트너스",
    "userInvestment": "userId7",
    "myCompanySelectedCount": 51510,
    "vmsInvestment": "20억",
    "compareSelectedCount": 15744
  },
  {
    "id": 8,
    "companyName": "메이저맵 8",
    "description": "높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다. 기술력과 창의성을 기반으로 차별화된 서비스를 운영하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "106억",
    "revenue": "427.8억",
    "employees": "392명",
    "investmentStage": "프리시리즈A",
    "investors": "프라이머,본엔젤스,에이티넘인베스트먼트",
    "userInvestment": "userId8",
    "myCompanySelectedCount": 39831,
    "vmsInvestment": "188억",
    "compareSelectedCount": 1204
  },
  {
    "id": 9,
    "companyName": "코멘토 9",
    "description": "국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "139억",
    "revenue": "298.0억",
    "employees": "492명",
    "investmentStage": "프리시리즈C",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId9",
    "myCompanySelectedCount": 32180,
    "vmsInvestment": "68억",
    "compareSelectedCount": 9213
  },
  {
    "id": 10,
    "companyName": "클래스101 10",
    "description": "고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 기술력과 창의성을 기반으로 차별화된 서비스를 운영하고 있습니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "768억",
    "revenue": "467.1억",
    "employees": "576명",
    "investmentStage": "프리시리즈A",
    "investors": "스마일게이트인베스트먼트,해시드,와이콤비네이터",
    "userInvestment": "userId10",
    "myCompanySelectedCount": 23269,
    "vmsInvestment": "13억",
    "compareSelectedCount": 2439
  },
  {
    "id": 11,
    "companyName": "엘리스그룹 11",
    "description": "이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 사용자의 편의성을 고려한 직관적인 UX/UI를 제공합니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "540억",
    "revenue": "631.0억",
    "employees": "62명",
    "investmentStage": "시드투자",
    "investors": "프라이머,본엔젤스,에이티넘인베스트먼트",
    "userInvestment": "userId11",
    "myCompanySelectedCount": 8614,
    "vmsInvestment": "73억",
    "compareSelectedCount": 12206
  },
  {
    "id": 12,
    "companyName": "클라썸 12",
    "description": "지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다. 국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "435억",
    "revenue": "38.2억",
    "employees": "559명",
    "investmentStage": "프리시리즈B",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId12",
    "myCompanySelectedCount": 23855,
    "vmsInvestment": "146억",
    "compareSelectedCount": 7363
  },
  {
    "id": 13,
    "companyName": "프리월린 13",
    "description": "이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다. 국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "710억",
    "revenue": "697.8억",
    "employees": "356명",
    "investmentStage": "시드투자",
    "investors": "한국산업은행,네이버,소프트뱅크",
    "userInvestment": "userId13",
    "myCompanySelectedCount": 48127,
    "vmsInvestment": "125억",
    "compareSelectedCount": 37800
  },
  {
    "id": 14,
    "companyName": "클래스101 14",
    "description": "높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다. 지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "413억",
    "revenue": "579.2억",
    "employees": "115명",
    "investmentStage": "시리즈C",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId14",
    "myCompanySelectedCount": 50320,
    "vmsInvestment": "51억",
    "compareSelectedCount": 49454
  },
  {
    "id": 15,
    "companyName": "엘리스그룹 15",
    "description": "국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "278억",
    "revenue": "236.6억",
    "employees": "398명",
    "investmentStage": "비공개",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId15",
    "myCompanySelectedCount": 39163,
    "vmsInvestment": "62억",
    "compareSelectedCount": 7445
  },
  {
    "id": 16,
    "companyName": "이팝소프트 16",
    "description": "높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "331억",
    "revenue": "250.6억",
    "employees": "240명",
    "investmentStage": "시리즈C",
    "investors": "프라이머,본엔젤스,에이티넘인베스트먼트",
    "userInvestment": "userId16",
    "myCompanySelectedCount": 41954,
    "vmsInvestment": "86억",
    "compareSelectedCount": 38355
  },
  {
    "id": 17,
    "companyName": "코드잇 17",
    "description": "사용자의 편의성을 고려한 직관적인 UX/UI를 제공합니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "766억",
    "revenue": "275.4억",
    "employees": "521명",
    "investmentStage": "시리즈B",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId17",
    "myCompanySelectedCount": 19636,
    "vmsInvestment": "32억",
    "compareSelectedCount": 9626
  },
  {
    "id": 18,
    "companyName": "인프랩 18",
    "description": "빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 사용자의 편의성을 고려한 직관적인 UX/UI를 제공합니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "167억",
    "revenue": "423.0억",
    "employees": "191명",
    "investmentStage": "프리시리즈A",
    "investors": "한국산업은행,네이버,소프트뱅크",
    "userInvestment": "userId18",
    "myCompanySelectedCount": 26354,
    "vmsInvestment": "75억",
    "compareSelectedCount": 24707
  },
  {
    "id": 19,
    "companyName": "넥스트러너스 19",
    "description": "이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "85억",
    "revenue": "27.3억",
    "employees": "60명",
    "investmentStage": "프리시리즈C",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId19",
    "myCompanySelectedCount": 30498,
    "vmsInvestment": "42억",
    "compareSelectedCount": 39203
  },
  {
    "id": 20,
    "companyName": "모레 20",
    "description": "고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 사용자의 편의성을 고려한 직관적인 UX/UI를 제공합니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "164억",
    "revenue": "684.2억",
    "employees": "539명",
    "investmentStage": "비공개",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId20",
    "myCompanySelectedCount": 24992,
    "vmsInvestment": "34억",
    "compareSelectedCount": 43902
  },
  {
    "id": 21,
    "companyName": "코멘토 21",
    "description": "지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "723억",
    "revenue": "462.5억",
    "employees": "271명",
    "investmentStage": "프리시리즈B",
    "investors": "캡스톤파트너스,케이비인베스트먼트,디쓰리쥬빌리파트너스",
    "userInvestment": "userId21",
    "myCompanySelectedCount": 55773,
    "vmsInvestment": "196억",
    "compareSelectedCount": 23394
  },
  {
    "id": 22,
    "companyName": "프리월린 22",
    "description": "사용자의 편의성을 고려한 직관적인 UX/UI를 제공합니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "503억",
    "revenue": "432.3억",
    "employees": "597명",
    "investmentStage": "비공개",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId22",
    "myCompanySelectedCount": 6196,
    "vmsInvestment": "111억",
    "compareSelectedCount": 41406
  },
  {
    "id": 23,
    "companyName": "넥스트러너스 23",
    "description": "높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다. 이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다. 사용자의 편의성을 고려한 직관적인 UX/UI를 제공합니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "562억",
    "revenue": "408.4억",
    "employees": "316명",
    "investmentStage": "시리즈B",
    "investors": "스마일게이트인베스트먼트,해시드,와이콤비네이터",
    "userInvestment": "userId23",
    "myCompanySelectedCount": 3735,
    "vmsInvestment": "190억",
    "compareSelectedCount": 13062
  },
  {
    "id": 24,
    "companyName": "로앤컴퍼니 24",
    "description": "높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다. 기술력과 창의성을 기반으로 차별화된 서비스를 운영하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "242억",
    "revenue": "625.8억",
    "employees": "463명",
    "investmentStage": "프리시리즈B",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId24",
    "myCompanySelectedCount": 58183,
    "vmsInvestment": "156억",
    "compareSelectedCount": 22953
  },
  {
    "id": 25,
    "companyName": "코멘토 25",
    "description": "이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다. 국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "455억",
    "revenue": "195.4억",
    "employees": "238명",
    "investmentStage": "프리시리즈B",
    "investors": "캡스톤파트너스,케이비인베스트먼트,디쓰리쥬빌리파트너스",
    "userInvestment": "userId25",
    "myCompanySelectedCount": 8964,
    "vmsInvestment": "178억",
    "compareSelectedCount": 34188
  },
  {
    "id": 26,
    "companyName": "넥스트러너스 26",
    "description": "지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다. 다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "657억",
    "revenue": "568.2억",
    "employees": "500명",
    "investmentStage": "시리즈A",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId26",
    "myCompanySelectedCount": 8844,
    "vmsInvestment": "111억",
    "compareSelectedCount": 32221
  },
  {
    "id": 27,
    "companyName": "이팝소프트 27",
    "description": "기술력과 창의성을 기반으로 차별화된 서비스를 운영하고 있습니다. 국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다. 지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다. 사용자의 편의성을 고려한 직관적인 UX/UI를 제공합니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "775억",
    "revenue": "241.1억",
    "employees": "423명",
    "investmentStage": "시드투자",
    "investors": "캡스톤파트너스,케이비인베스트먼트,디쓰리쥬빌리파트너스",
    "userInvestment": "userId27",
    "myCompanySelectedCount": 53038,
    "vmsInvestment": "112억",
    "compareSelectedCount": 40769
  },
  {
    "id": 28,
    "companyName": "인프랩 28",
    "description": "다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "258억",
    "revenue": "601.3억",
    "employees": "375명",
    "investmentStage": "시리즈C",
    "investors": "스마일게이트인베스트먼트,해시드,와이콤비네이터",
    "userInvestment": "userId28",
    "myCompanySelectedCount": 58630,
    "vmsInvestment": "56억",
    "compareSelectedCount": 30370
  },
  {
    "id": 29,
    "companyName": "코드잇 29",
    "description": "이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "548억",
    "revenue": "506.4억",
    "employees": "449명",
    "investmentStage": "시드투자",
    "investors": "캡스톤파트너스,케이비인베스트먼트,디쓰리쥬빌리파트너스",
    "userInvestment": "userId29",
    "myCompanySelectedCount": 7817,
    "vmsInvestment": "106억",
    "compareSelectedCount": 7105
  },
  {
    "id": 30,
    "companyName": "모레 30",
    "description": "높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "392억",
    "revenue": "432.7억",
    "employees": "144명",
    "investmentStage": "프리시리즈C",
    "investors": "캡스톤파트너스,케이비인베스트먼트,디쓰리쥬빌리파트너스",
    "userInvestment": "userId30",
    "myCompanySelectedCount": 2150,
    "vmsInvestment": "180억",
    "compareSelectedCount": 17590
  },
  {
    "id": 31,
    "companyName": "엘리스그룹 31",
    "description": "지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "667억",
    "revenue": "616.5억",
    "employees": "580명",
    "investmentStage": "프리시리즈A",
    "investors": "캡스톤파트너스,케이비인베스트먼트,디쓰리쥬빌리파트너스",
    "userInvestment": "userId31",
    "myCompanySelectedCount": 18709,
    "vmsInvestment": "167억",
    "compareSelectedCount": 45229
  },
  {
    "id": 32,
    "companyName": "클라썸 32",
    "description": "사용자의 편의성을 고려한 직관적인 UX/UI를 제공합니다. 국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "795억",
    "revenue": "308.2억",
    "employees": "572명",
    "investmentStage": "프리시리즈B",
    "investors": "캡스톤파트너스,케이비인베스트먼트,디쓰리쥬빌리파트너스",
    "userInvestment": "userId32",
    "myCompanySelectedCount": 16787,
    "vmsInvestment": "123억",
    "compareSelectedCount": 23553
  },
  {
    "id": 33,
    "companyName": "프리월린 33",
    "description": "빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다. 기술력과 창의성을 기반으로 차별화된 서비스를 운영하고 있습니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "130억",
    "revenue": "223.4억",
    "employees": "503명",
    "investmentStage": "시리즈B",
    "investors": "프라이머,본엔젤스,에이티넘인베스트먼트",
    "userInvestment": "userId33",
    "myCompanySelectedCount": 48989,
    "vmsInvestment": "105억",
    "compareSelectedCount": 29357
  },
  {
    "id": 34,
    "companyName": "모레 34",
    "description": "높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "699억",
    "revenue": "91.1억",
    "employees": "28명",
    "investmentStage": "시리즈B",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId34",
    "myCompanySelectedCount": 31570,
    "vmsInvestment": "123억",
    "compareSelectedCount": 39914
  },
  {
    "id": 35,
    "companyName": "클라썸 35",
    "description": "높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다. 국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "299억",
    "revenue": "242.3억",
    "employees": "305명",
    "investmentStage": "시드투자",
    "investors": "캡스톤파트너스,케이비인베스트먼트,디쓰리쥬빌리파트너스",
    "userInvestment": "userId35",
    "myCompanySelectedCount": 7771,
    "vmsInvestment": "196억",
    "compareSelectedCount": 18395
  },
  {
    "id": 36,
    "companyName": "메이저맵 36",
    "description": "다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다. 기술력과 창의성을 기반으로 차별화된 서비스를 운영하고 있습니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "103억",
    "revenue": "504.5억",
    "employees": "466명",
    "investmentStage": "시리즈C",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId36",
    "myCompanySelectedCount": 11326,
    "vmsInvestment": "72억",
    "compareSelectedCount": 10681
  },
  {
    "id": 37,
    "companyName": "코멘토 37",
    "description": "지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "665억",
    "revenue": "590.3억",
    "employees": "425명",
    "investmentStage": "프리시리즈A",
    "investors": "한국산업은행,네이버,소프트뱅크",
    "userInvestment": "userId37",
    "myCompanySelectedCount": 41367,
    "vmsInvestment": "128억",
    "compareSelectedCount": 32752
  },
  {
    "id": 38,
    "companyName": "로앤컴퍼니 38",
    "description": "고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 기술력과 창의성을 기반으로 차별화된 서비스를 운영하고 있습니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "652억",
    "revenue": "518.1억",
    "employees": "36명",
    "investmentStage": "프리시리즈B",
    "investors": "스마일게이트인베스트먼트,해시드,와이콤비네이터",
    "userInvestment": "userId38",
    "myCompanySelectedCount": 3141,
    "vmsInvestment": "100억",
    "compareSelectedCount": 40163
  },
  {
    "id": 39,
    "companyName": "프리월린 39",
    "description": "높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다. 빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "547억",
    "revenue": "37.1억",
    "employees": "430명",
    "investmentStage": "프리시리즈B",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId39",
    "myCompanySelectedCount": 56206,
    "vmsInvestment": "191억",
    "compareSelectedCount": 42326
  },
  {
    "id": 40,
    "companyName": "프리월린 40",
    "description": "고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 기술력과 창의성을 기반으로 차별화된 서비스를 운영하고 있습니다. 국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "630억",
    "revenue": "109.6억",
    "employees": "40명",
    "investmentStage": "프리시리즈B",
    "investors": "한국산업은행,네이버,소프트뱅크",
    "userInvestment": "userId40",
    "myCompanySelectedCount": 28263,
    "vmsInvestment": "151억",
    "compareSelectedCount": 17267
  },
  {
    "id": 41,
    "companyName": "인프랩 41",
    "description": "국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "520억",
    "revenue": "672.9억",
    "employees": "303명",
    "investmentStage": "시리즈C",
    "investors": "캡스톤파트너스,케이비인베스트먼트,디쓰리쥬빌리파트너스",
    "userInvestment": "userId41",
    "myCompanySelectedCount": 13621,
    "vmsInvestment": "126억",
    "compareSelectedCount": 45966
  },
  {
    "id": 42,
    "companyName": "엘리스그룹 42",
    "description": "사용자의 편의성을 고려한 직관적인 UX/UI를 제공합니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "710억",
    "revenue": "682.9억",
    "employees": "125명",
    "investmentStage": "프리시리즈B",
    "investors": "프라이머,본엔젤스,에이티넘인베스트먼트",
    "userInvestment": "userId42",
    "myCompanySelectedCount": 52358,
    "vmsInvestment": "68억",
    "compareSelectedCount": 28897
  },
  {
    "id": 43,
    "companyName": "클래스101 43",
    "description": "국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다. 사용자의 편의성을 고려한 직관적인 UX/UI를 제공합니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "590억",
    "revenue": "41.8억",
    "employees": "129명",
    "investmentStage": "비공개",
    "investors": "스마일게이트인베스트먼트,해시드,와이콤비네이터",
    "userInvestment": "userId43",
    "myCompanySelectedCount": 17002,
    "vmsInvestment": "41억",
    "compareSelectedCount": 14702
  },
  {
    "id": 44,
    "companyName": "프리월린 44",
    "description": "국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다. 이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다. 다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "359억",
    "revenue": "609.9억",
    "employees": "89명",
    "investmentStage": "시리즈A",
    "investors": "한국산업은행,네이버,소프트뱅크",
    "userInvestment": "userId44",
    "myCompanySelectedCount": 39892,
    "vmsInvestment": "140억",
    "compareSelectedCount": 13144
  },
  {
    "id": 45,
    "companyName": "아이헤이트플라잉버그스 45",
    "description": "높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다. 빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "428억",
    "revenue": "513.6억",
    "employees": "75명",
    "investmentStage": "시리즈C",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId45",
    "myCompanySelectedCount": 17530,
    "vmsInvestment": "41억",
    "compareSelectedCount": 47623
  },
  {
    "id": 46,
    "companyName": "뤼이드 46",
    "description": "이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다. 기술력과 창의성을 기반으로 차별화된 서비스를 운영하고 있습니다. 빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "408억",
    "revenue": "374.1억",
    "employees": "116명",
    "investmentStage": "시리즈A",
    "investors": "한국산업은행,네이버,소프트뱅크",
    "userInvestment": "userId46",
    "myCompanySelectedCount": 47752,
    "vmsInvestment": "152억",
    "compareSelectedCount": 38926
  },
  {
    "id": 47,
    "companyName": "코멘토 47",
    "description": "기술력과 창의성을 기반으로 차별화된 서비스를 운영하고 있습니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 사용자의 편의성을 고려한 직관적인 UX/UI를 제공합니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "141억",
    "revenue": "205.2억",
    "employees": "555명",
    "investmentStage": "시드투자",
    "investors": "스마일게이트인베스트먼트,해시드,와이콤비네이터",
    "userInvestment": "userId47",
    "myCompanySelectedCount": 51542,
    "vmsInvestment": "41억",
    "compareSelectedCount": 31414
  },
  {
    "id": 48,
    "companyName": "클래스101 48",
    "description": "국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "266억",
    "revenue": "546.4억",
    "employees": "76명",
    "investmentStage": "시리즈B",
    "investors": "한국산업은행,네이버,소프트뱅크",
    "userInvestment": "userId48",
    "myCompanySelectedCount": 53404,
    "vmsInvestment": "183억",
    "compareSelectedCount": 38333
  },
  {
    "id": 49,
    "companyName": "엘리스그룹 49",
    "description": "기술력과 창의성을 기반으로 차별화된 서비스를 운영하고 있습니다. 지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다. 다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "557억",
    "revenue": "97.2억",
    "employees": "213명",
    "investmentStage": "시드투자",
    "investors": "스마일게이트인베스트먼트,해시드,와이콤비네이터",
    "userInvestment": "userId49",
    "myCompanySelectedCount": 33995,
    "vmsInvestment": "99억",
    "compareSelectedCount": 8912
  },
  {
    "id": 50,
    "companyName": "인프랩 50",
    "description": "국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "332억",
    "revenue": "139.0억",
    "employees": "325명",
    "investmentStage": "시리즈A",
    "investors": "캡스톤파트너스,케이비인베스트먼트,디쓰리쥬빌리파트너스",
    "userInvestment": "userId50",
    "myCompanySelectedCount": 29606,
    "vmsInvestment": "85억",
    "compareSelectedCount": 24546
  },
  {
    "id": 51,
    "companyName": "넥스트러너스 51",
    "description": "이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다. 사용자의 편의성을 고려한 직관적인 UX/UI를 제공합니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "105억",
    "revenue": "219.5억",
    "employees": "372명",
    "investmentStage": "시드투자",
    "investors": "한국산업은행,네이버,소프트뱅크",
    "userInvestment": "userId51",
    "myCompanySelectedCount": 59539,
    "vmsInvestment": "146억",
    "compareSelectedCount": 48879
  },
  {
    "id": 52,
    "companyName": "엘리스그룹 52",
    "description": "고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다. 빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "161억",
    "revenue": "180.9억",
    "employees": "359명",
    "investmentStage": "비공개",
    "investors": "캡스톤파트너스,케이비인베스트먼트,디쓰리쥬빌리파트너스",
    "userInvestment": "userId52",
    "myCompanySelectedCount": 24506,
    "vmsInvestment": "31억",
    "compareSelectedCount": 49528
  },
  {
    "id": 53,
    "companyName": "코드스테이츠 53",
    "description": "높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다. 지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "657억",
    "revenue": "141.8억",
    "employees": "297명",
    "investmentStage": "시드투자",
    "investors": "프라이머,본엔젤스,에이티넘인베스트먼트",
    "userInvestment": "userId53",
    "myCompanySelectedCount": 1332,
    "vmsInvestment": "135억",
    "compareSelectedCount": 30697
  },
  {
    "id": 54,
    "companyName": "클라썸 54",
    "description": "기술력과 창의성을 기반으로 차별화된 서비스를 운영하고 있습니다. 다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "305억",
    "revenue": "628.9억",
    "employees": "284명",
    "investmentStage": "시리즈B",
    "investors": "프라이머,본엔젤스,에이티넘인베스트먼트",
    "userInvestment": "userId54",
    "myCompanySelectedCount": 24507,
    "vmsInvestment": "33억",
    "compareSelectedCount": 26248
  },
  {
    "id": 55,
    "companyName": "로앤컴퍼니 55",
    "description": "빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다. 이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다. 국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "147억",
    "revenue": "534.6억",
    "employees": "349명",
    "investmentStage": "시리즈A",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId55",
    "myCompanySelectedCount": 43092,
    "vmsInvestment": "60억",
    "compareSelectedCount": 37059
  },
  {
    "id": 56,
    "companyName": "이팝소프트 56",
    "description": "이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다. 국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "484억",
    "revenue": "587.3억",
    "employees": "416명",
    "investmentStage": "프리시리즈C",
    "investors": "한국산업은행,네이버,소프트뱅크",
    "userInvestment": "userId56",
    "myCompanySelectedCount": 3424,
    "vmsInvestment": "154억",
    "compareSelectedCount": 39075
  },
  {
    "id": 57,
    "companyName": "클라썸 57",
    "description": "기술력과 창의성을 기반으로 차별화된 서비스를 운영하고 있습니다. 다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다. 국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "94억",
    "revenue": "194.2억",
    "employees": "153명",
    "investmentStage": "시리즈A",
    "investors": "캡스톤파트너스,케이비인베스트먼트,디쓰리쥬빌리파트너스",
    "userInvestment": "userId57",
    "myCompanySelectedCount": 46115,
    "vmsInvestment": "39억",
    "compareSelectedCount": 16575
  },
  {
    "id": 58,
    "companyName": "프리월린 58",
    "description": "다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다. 국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "294억",
    "revenue": "525.3억",
    "employees": "207명",
    "investmentStage": "프리시리즈B",
    "investors": "캡스톤파트너스,케이비인베스트먼트,디쓰리쥬빌리파트너스",
    "userInvestment": "userId58",
    "myCompanySelectedCount": 40281,
    "vmsInvestment": "196억",
    "compareSelectedCount": 48867
  },
  {
    "id": 59,
    "companyName": "코드스테이츠 59",
    "description": "국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다. 다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "467억",
    "revenue": "167.1억",
    "employees": "500명",
    "investmentStage": "프리시리즈A",
    "investors": "스마일게이트인베스트먼트,해시드,와이콤비네이터",
    "userInvestment": "userId59",
    "myCompanySelectedCount": 24240,
    "vmsInvestment": "148억",
    "compareSelectedCount": 11322
  },
  {
    "id": 60,
    "companyName": "프리월린 60",
    "description": "고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다. 다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "396억",
    "revenue": "492.2억",
    "employees": "58명",
    "investmentStage": "시드투자",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId60",
    "myCompanySelectedCount": 23827,
    "vmsInvestment": "154억",
    "compareSelectedCount": 44554
  },
  {
    "id": 61,
    "companyName": "엘리스그룹 61",
    "description": "이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "747억",
    "revenue": "369.7억",
    "employees": "448명",
    "investmentStage": "프리시리즈C",
    "investors": "스마일게이트인베스트먼트,해시드,와이콤비네이터",
    "userInvestment": "userId61",
    "myCompanySelectedCount": 10867,
    "vmsInvestment": "133억",
    "compareSelectedCount": 31950
  },
  {
    "id": 62,
    "companyName": "이팝소프트 62",
    "description": "이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다. 이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "494억",
    "revenue": "689.5억",
    "employees": "289명",
    "investmentStage": "프리시리즈A",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId62",
    "myCompanySelectedCount": 16910,
    "vmsInvestment": "111억",
    "compareSelectedCount": 40590
  },
  {
    "id": 63,
    "companyName": "아이헤이트플라잉버그스 63",
    "description": "지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "224억",
    "revenue": "310.9억",
    "employees": "178명",
    "investmentStage": "시드투자",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId63",
    "myCompanySelectedCount": 7202,
    "vmsInvestment": "145억",
    "compareSelectedCount": 13126
  },
  {
    "id": 64,
    "companyName": "모레 64",
    "description": "사용자의 편의성을 고려한 직관적인 UX/UI를 제공합니다. 다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "760억",
    "revenue": "386.4억",
    "employees": "598명",
    "investmentStage": "시리즈B",
    "investors": "캡스톤파트너스,케이비인베스트먼트,디쓰리쥬빌리파트너스",
    "userInvestment": "userId64",
    "myCompanySelectedCount": 39607,
    "vmsInvestment": "163억",
    "compareSelectedCount": 10364
  },
  {
    "id": 65,
    "companyName": "팀스파르타 65",
    "description": "고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다. 기술력과 창의성을 기반으로 차별화된 서비스를 운영하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "671억",
    "revenue": "94.7억",
    "employees": "38명",
    "investmentStage": "프리시리즈B",
    "investors": "한국산업은행,네이버,소프트뱅크",
    "userInvestment": "userId65",
    "myCompanySelectedCount": 33933,
    "vmsInvestment": "49억",
    "compareSelectedCount": 11233
  },
  {
    "id": 66,
    "companyName": "뤼이드 66",
    "description": "사용자의 편의성을 고려한 직관적인 UX/UI를 제공합니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 기술력과 창의성을 기반으로 차별화된 서비스를 운영하고 있습니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "269억",
    "revenue": "111.8억",
    "employees": "246명",
    "investmentStage": "프리시리즈A",
    "investors": "스마일게이트인베스트먼트,해시드,와이콤비네이터",
    "userInvestment": "userId66",
    "myCompanySelectedCount": 41700,
    "vmsInvestment": "167억",
    "compareSelectedCount": 7346
  },
  {
    "id": 67,
    "companyName": "팀스파르타 67",
    "description": "이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "593억",
    "revenue": "23.4억",
    "employees": "113명",
    "investmentStage": "프리시리즈A",
    "investors": "프라이머,본엔젤스,에이티넘인베스트먼트",
    "userInvestment": "userId67",
    "myCompanySelectedCount": 33359,
    "vmsInvestment": "179억",
    "compareSelectedCount": 1119
  },
  {
    "id": 68,
    "companyName": "넥스트러너스 68",
    "description": "사용자의 편의성을 고려한 직관적인 UX/UI를 제공합니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "97억",
    "revenue": "55.6억",
    "employees": "485명",
    "investmentStage": "시리즈C",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId68",
    "myCompanySelectedCount": 45360,
    "vmsInvestment": "84억",
    "compareSelectedCount": 47024
  },
  {
    "id": 69,
    "companyName": "클라썸 69",
    "description": "기술력과 창의성을 기반으로 차별화된 서비스를 운영하고 있습니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "724억",
    "revenue": "576.5억",
    "employees": "441명",
    "investmentStage": "프리시리즈B",
    "investors": "스마일게이트인베스트먼트,해시드,와이콤비네이터",
    "userInvestment": "userId69",
    "myCompanySelectedCount": 57705,
    "vmsInvestment": "21억",
    "compareSelectedCount": 24778
  },
  {
    "id": 70,
    "companyName": "코드스테이츠 70",
    "description": "높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다. 빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "185억",
    "revenue": "440.2억",
    "employees": "300명",
    "investmentStage": "시리즈A",
    "investors": "캡스톤파트너스,케이비인베스트먼트,디쓰리쥬빌리파트너스",
    "userInvestment": "userId70",
    "myCompanySelectedCount": 12572,
    "vmsInvestment": "16억",
    "compareSelectedCount": 12241
  },
  {
    "id": 71,
    "companyName": "팀스파르타 71",
    "description": "고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "126억",
    "revenue": "668.3억",
    "employees": "119명",
    "investmentStage": "시리즈A",
    "investors": "프라이머,본엔젤스,에이티넘인베스트먼트",
    "userInvestment": "userId71",
    "myCompanySelectedCount": 54920,
    "vmsInvestment": "108억",
    "compareSelectedCount": 19403
  },
  {
    "id": 72,
    "companyName": "팀스파르타 72",
    "description": "이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다. 이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "331억",
    "revenue": "532.8억",
    "employees": "94명",
    "investmentStage": "비공개",
    "investors": "캡스톤파트너스,케이비인베스트먼트,디쓰리쥬빌리파트너스",
    "userInvestment": "userId72",
    "myCompanySelectedCount": 58477,
    "vmsInvestment": "38억",
    "compareSelectedCount": 14571
  },
  {
    "id": 73,
    "companyName": "클래스101 73",
    "description": "이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다. 빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "644억",
    "revenue": "489.2억",
    "employees": "385명",
    "investmentStage": "프리시리즈B",
    "investors": "프라이머,본엔젤스,에이티넘인베스트먼트",
    "userInvestment": "userId73",
    "myCompanySelectedCount": 50871,
    "vmsInvestment": "36억",
    "compareSelectedCount": 10119
  },
  {
    "id": 74,
    "companyName": "로앤컴퍼니 74",
    "description": "다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "214억",
    "revenue": "614.8억",
    "employees": "330명",
    "investmentStage": "비공개",
    "investors": "프라이머,본엔젤스,에이티넘인베스트먼트",
    "userInvestment": "userId74",
    "myCompanySelectedCount": 2979,
    "vmsInvestment": "80억",
    "compareSelectedCount": 28156
  },
  {
    "id": 75,
    "companyName": "뤼이드 75",
    "description": "지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다. 다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "286억",
    "revenue": "695.9억",
    "employees": "320명",
    "investmentStage": "프리시리즈A",
    "investors": "한국산업은행,네이버,소프트뱅크",
    "userInvestment": "userId75",
    "myCompanySelectedCount": 4371,
    "vmsInvestment": "151억",
    "compareSelectedCount": 4035
  },
  {
    "id": 76,
    "companyName": "메이저맵 76",
    "description": "기술력과 창의성을 기반으로 차별화된 서비스를 운영하고 있습니다. 이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다. 빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "80억",
    "revenue": "475.2억",
    "employees": "281명",
    "investmentStage": "프리시리즈B",
    "investors": "프라이머,본엔젤스,에이티넘인베스트먼트",
    "userInvestment": "userId76",
    "myCompanySelectedCount": 3609,
    "vmsInvestment": "34억",
    "compareSelectedCount": 9176
  },
  {
    "id": 77,
    "companyName": "코드잇 77",
    "description": "국내외 다양한 기관과 협업하여 글로벌 시장에 진출하고 있습니다. 빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다. 기술력과 창의성을 기반으로 차별화된 서비스를 운영하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "80억",
    "revenue": "165.4억",
    "employees": "105명",
    "investmentStage": "시드투자",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId77",
    "myCompanySelectedCount": 42888,
    "vmsInvestment": "39억",
    "compareSelectedCount": 35546
  },
  {
    "id": 78,
    "companyName": "이팝소프트 78",
    "description": "이 스타트업은 혁신적인 기술을 바탕으로 빠르게 성장하고 있습니다. 다양한 분야에서 경험을 쌓은 팀원들이 모여 새로운 가치를 창출하고 있습니다. 지속 가능한 성장을 위해 ESG 경영을 실천하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "402억",
    "revenue": "482.7억",
    "employees": "581명",
    "investmentStage": "시리즈B",
    "investors": "스트롱벤처스,미래에셋,카카오벤처스",
    "userInvestment": "userId78",
    "myCompanySelectedCount": 28069,
    "vmsInvestment": "96억",
    "compareSelectedCount": 15937
  },
  {
    "id": 79,
    "companyName": "넥스트러너스 79",
    "description": "높은 완주율과 만족도를 자랑하는 프로그램을 제공합니다. 이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다. 고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "365억",
    "revenue": "478.0억",
    "employees": "385명",
    "investmentStage": "비공개",
    "investors": "캡스톤파트너스,케이비인베스트먼트,디쓰리쥬빌리파트너스",
    "userInvestment": "userId79",
    "myCompanySelectedCount": 33147,
    "vmsInvestment": "131억",
    "compareSelectedCount": 40864
  },
  {
    "id": 80,
    "companyName": "아이헤이트플라잉버그스 80",
    "description": "고객 중심의 서비스를 통해 시장에서 높은 평가를 받고 있습니다. 이 기업은 데이터 기반의 전략으로 경쟁력을 강화하고 있습니다. 빠르게 변화하는 시장에 유연하게 대응하며 제품을 개선하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "441억",
    "revenue": "524.4억",
    "employees": "591명",
    "investmentStage": "시드투자",
    "investors": "캡스톤파트너스,케이비인베스트먼트,디쓰리쥬빌리파트너스",
    "userInvestment": "userId80",
    "myCompanySelectedCount": 25188,
    "vmsInvestment": "140억",
    "compareSelectedCount": 13680
  }
];