export const invInitialData = [
  {
    "id": 1,
    "companyName": "코드잇",
    "description": "코드잇은 '온라인 코딩 교육 서비스'를 운영하는 EdTech 스타트업입니다. 코딩 교육과 데이터 사이언스 교육에 대한 수요는 급격히 늘어나고 있지만, 아직까지 좋은 교육 서비스를 찾기란 쉽지 않습니다. 이를 해결하고자 코드잇은 모든 강의를 자체 제작하여 퀄리티 높은 콘텐츠를 제공하고, 동시에 코딩 교육에 최적화된 플랫폼을 개발하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "140억",
    "revenue": "172.4억",
    "employees": "115명",
    "investmentStage": "시리즈B",
    "investors": "에이벤처스,펄어비스캐피탈,퓨처플레이,신한캐피탈,산은캐피탈,대성창업투자",
    "userInvestment": "userId1",
    "myCompanySelectedCount": 123
  },
  {
    "id": 2,
    "companyName": "팀스파르타",
    "description": "온라인 코딩 교육 서비스를 제공하고 있는 팀스파르타는 2019년 4월 ‘스파르타코딩클럽’을 시작으로, 꾸준히 순이익을 내며 개발자 양성 부트캠프 ‘항해99’, 직장인 창업 부트캠프 ‘{창}’을 운영하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "130억",
    "revenue": "606.5억",
    "employees": "241명",
    "investmentStage": "시리즈A",
    "investors": "위벤처스,캡스톤파트너스,스마일게이트인베스트먼트,디에스자산운용,케이비인베스트먼트",
    "userInvestment": "userId2",
    "myCompanySelectedCount": 51245
  },
  {
    "id": 3,
    "companyName": "인프랩",
    "description": "인프랩은 IT 교육 플랫폼 '인프런'과 IT 인재 채용 서비스 '랠릿'을 운영하는 기업입니다. 인프런의 경우, 2022년 1분기 전년 동기 대비 160% 증가한 수치인 매출 41억 원을 기록하고, 회원 가입자 수 90만 명을 돌파하며 큰 성과를 내고 있습니다.  또한, 2022년 상반기 IT 전문 커리어 플랫폼 '랠릿'을 출시하며...",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "65억",
    "revenue": "70.4억",
    "employees": "80명",
    "investmentStage": "시리즈A",
    "investors": "티비티,본엔젤스벤처파트너스,한국투자파트너스,미래에셋캐피탈",
    "userInvestment": "userId3",
    "myCompanySelectedCount": 32
  },
  {
    "id": 4,
    "companyName": "뤼이드",
    "description": "뤼이드(Riiid!)는 데이터 기술을 통해 교육 업계의 창조적 파괴에 도전하는 기술 기반 교육 스타트업입니다. ‘제거하다’는 뜻의 영어 단어 ‘리드(Rid)’를 위트있게 표현한 뤼이드(Riiid!)라는 이름에는 기술로 세상의 불편함을 제거한다는 뤼이더스(Riiiders)의 비전이 담겨 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "2809억",
    "revenue": "77억",
    "employees": "143명",
    "investmentStage": "비공개",
    "investors": "소프트뱅크비전펀드,한국산업은행,아이엠인베스트먼트,인터베스트",
    "userInvestment": "userId4",
    "myCompanySelectedCount": 62346324
  },
  {
    "id": 5,
    "companyName": "엘리스그룹",
    "description": "엘리스는 자체 개발한 온라인 프로그래밍 실습 플랫폼을 기반으로 새로운 컴퓨터 사이언스 교육 패러다임을 만드는 기업입니다. SK그룹, 기업은행, 현대모비스, CJ올리브네트웍스, LG CNS, 삼성SDS 등 주요 테크 중심 기업에서 디지털 트랜스포메이션 교육을 위해 엘리스 플랫폼 및 교육 콘텐츠를 사용하고...",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "333억",
    "revenue": "351.7억",
    "employees": "134명",
    "investmentStage": "비공개",
    "investors": "버텍스,삼성벤처투자,한국산업은행,네이버",
    "userInvestment": "userId5",
    "myCompanySelectedCount": 266
  },
  {
    "id": 6,
    "companyName": "아이헤이트플라잉버그스",
    "description": "아이헤이트플라잉버그스는 `모두가 질 높은 교육의 기회를 가질 수 있는 세상` 목표로 하고 있습니다. AI로 취약점을 분석해주고, 1:1로 원격 학습 관리로 공부 습관을 형성해주는 `밀당PT` 서비스를 운영하고 있습니다. 서비스 초기의 학습 완강률 13%이었지만 2년 만에 92%로 끌어 올리면서 서비스를 확장...",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "635억",
    "revenue": "376억",
    "employees": "522명",
    "investmentStage": "시리즈C",
    "investors": "한국산업은행,딥다이브파트너스,신한은행,아이비케이캐피탈",
    "userInvestment": "userId6",
    "myCompanySelectedCount": 2
  },
  {
    "id": 7,
    "companyName": "코드스테이츠",
    "description": "코드스테이츠는 수동적인 주입식 교육이 아니라, 자기주도적으로 학습하는 코딩 부트캠프를 운영합니다. 또한 엔지니어 커뮤니티를 기반으로 엔지니어들과 소통하며 실제 현장에서 필요한 인재를 양성하는 교육을 하기 위해 노력하고 있습니다. 코드스테이츠는 학습자의 이전 배경, 경제적 상황과 상관없이 본인의 잠재력을 최대한 발휘할 수 있도록 교육, 채용, 금융 서비스를 제공합니다. 코드스테이츠는 학습자들이 새로운 커리어를 시작하기 위한 최고의 기관이 될 것입니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "40억",
    "revenue": "287억",
    "employees": "25명",
    "investmentStage": "프리시리즈A",
    "investors": "스트롱벤처스,해시드,프라이머,서울산업진흥원",
    "userInvestment": "userId7",
    "myCompanySelectedCount": 344
  },
  {
    "id": 8,
    "companyName": "넥스트러너스",
    "description": "제이알코딩연구소(Jr Coding Lab)는 2016년에 설립된 교육 프로그램개발 분야의 대전광역시에 위치한 한국 스타트업입니다. 아이들이 코딩을 어떻게 더 재미있고 어렵지 않게 학습할 수 있을까라는 질문에서 시작된 코딩 교육 스타트업입니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "비공개",
    "revenue": "40억",
    "employees": "47명",
    "investmentStage": "시드투자",
    "investors": "인포뱅크",
    "userInvestment": "userId8",
    "myCompanySelectedCount": 34
  },
  {
    "id": 9,
    "companyName": "코멘토",
    "description": "코멘토는 커리어 커뮤니티 및 교육 프로그램을 운영하는 기업으로, 취준생들의 커리어 시작과 성장을 도와주기 위해 필요한 각종 서비스를 제공합니다. 누적 가입자 90만 명, 월 평균 35만 명이 방문하는 커뮤니티를 운영하며, 전국 130여 개 이상 대학 및 지자체, 교육기관과 연결되어 있습니다. 또한, 4~6주간 LIVE로 배울 수 있는 직무부트캠프와 실무PT를 운영하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "47억",
    "revenue": "102.2억",
    "employees": "50명",
    "investmentStage": "비공개",
    "investors": "와이비엠,해시드벤처스,500스타트업스매니지먼트코리아",
    "userInvestment": "userId9",
    "myCompanySelectedCount": 53
  },
  {
    "id": 10,
    "companyName": "모레",
    "description": "모레(MOREH)는 토종 슈퍼컴퓨터 ‘천둥’을 개발한 서울대 매니코어프로그래밍연구단 출신 인재들이 설립한 AI 소프트웨어 스타트업입니다. 각종 AI 반도체·인프라·서비스를 국산화하여 더 많은 기업이 시장에 진출할 수 있도록 돕고, 새로운 AI 소프트웨어 주도권을 잡는 것이 목표입니다. 2023년 7월, 고객사인 KT, KT클라우드와 함께 ‘한국형 AI 풀스택’ 프로젝트에 참여했고, 10월에 미국 반도체 기업 AMD와 전략적 파트너십을 맺은 동시에 투자를 유치했습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "450억",
    "revenue": "7.3억",
    "employees": "100명",
    "investmentStage": "시리즈B",
    "investors": "케이티,에이엠디,스마일게이트인베스트먼트",
    "userInvestment": "userId10",
    "myCompanySelectedCount": 656
  },
  {
    "id": 11,
    "companyName": "로앤컴퍼니",
    "description": "로앤컴퍼니는 나의 상황에 맞는 상담사례 및 변호사를 찾고, 법률상담을 제공하는 법률전문기업입니다. 법률시장의 변화는 현재 법조계에 종사하는 수 많은 법조인들에게는 위협이자 동시에 큰 기회이기도 합니다. 로앤컴퍼니는 급변하는 대한민국 법률시장에서 새로운 기회를 창출하고자 합니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "400억",
    "revenue": "94.2억",
    "employees": "59명",
    "investmentStage": "프리시리즈C",
    "investors": "고벤처엔젤클럽,대교인베스트먼트,디쓰리쥬빌리파트너스,디에스씨인베스트먼트",
    "userInvestment": "userId11",
    "myCompanySelectedCount": 67
  },
  {
    "id": 12,
    "companyName": "클라썸",
    "description": "클라썸은 학생들과 교사의 소통을 쉽고, 간편하고, 스마트하게 만들어주는 수업 별 소통 플랫폼입니다. 클라썸은 수동적인 수업이 아닌, 학생들과 교사가 함께 만들어가는 능동적인 수업을 위한 커뮤니케이션을 책임집니다. 실제 사용자의 94%가 클라썸을 통해 학습 효율이 향상되었고, 77%가 교사, 조교와 친밀도가 높아졌다고 응답하였습니다. 2017년부터 서비스(Android/iOS앱, 웹사이트)를 운영하였고, 2018 Microsoft Imagine Cup World Finalist 선정, 제7회 정주영창업경진대회 대상, 동아시아 최초 Facebook 인큐베이팅 남산랩 1기 등의 이력을 가지고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "225억",
    "revenue": "15.6억",
    "employees": "70명",
    "investmentStage": "프리시리즈B",
    "investors": "두나무앤파트너스,스마일게이트인베스트먼트,벡베이슨캐피탈,카이스트청년창업투자지주",
    "userInvestment": "userId12",
    "myCompanySelectedCount": 7
  },
  {
    "id": 13,
    "companyName": "클래스101",
    "description": "클래스101은 온라인 클래스 구독 플랫폼 '클래스101+'를 운영하는 기업입니다. 2018년 '클래스101'을 런칭하고, 2022년 8월 구독 방식으로 서비스 개편, 12월 한국/미국/일본 글로벌 통합 버전 개편 등 서비스 확장을 지속적으로 해왔으며, 2023년 5월 기준 유료 구독자수 15만명을, 월간 거래액 160억원을 달성했습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "771억",
    "revenue": "324.9억",
    "employees": "84명",
    "investmentStage": "시리즈B",
    "investors": "스트롱벤처스,굿워터캐피털,미래에셋벤처투자,고위드",
    "userInvestment": "userId13",
    "myCompanySelectedCount": 46
  },
  {
    "id": 14,
    "companyName": "프리월린",
    "description": "프리윌린은 ‘교육을 더 스마트하게, 더 많은 사람들이 누리도록’이라는 미션을 가진 에듀테크 기업입니다. 수학 선생님의 학습지 제작, 수업준비를 도와주는 플랫폼 ‘매쓰플랫’을 운영하고 있습니다. 300여개의 중고등학교와 5000여개의 수학학원에서 서비스를 이용하고 있습니다. 교실에서 학생과 선생님 모두가 만족할 수 있는 개별 맞춤형 교육이 가능하도록 서비스를 개발하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "120억",
    "revenue": "159.8억",
    "employees": "143명",
    "investmentStage": "시리즈B",
    "investors": "스마일게이트인베스트먼트,우리벤처파트너스,케이비증권",
    "userInvestment": "userId14",
    "myCompanySelectedCount": 3
  },
  {
    "id": 15,
    "companyName": "이팝소프트",
    "description": "2018년에 설립되어 내 생각과 의도를 즉시 영어로 표현할 수 있도록 지원하는 글로벌 영어 학습 플랫폼 제작 기업입니다. 2022년 기준 3억분 이상의 누적 학습 시간과 7억개 이상의 학습 문제 수를 기록하고 있습니다. 실사용자들의 피드백을 통해 더 나은 서비스를 제공할 수 있도록 계속해서 업데이트를 하고 있습니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "105억",
    "revenue": "220억",
    "employees": "62명",
    "investmentStage": "시리즈A",
    "investors": "에이티넘인베스트먼트,본엔젤스벤처파트너스,팁스",
    "userInvestment": "userId15",
    "myCompanySelectedCount": 345
  },
  {
    "id": 16,
    "companyName": "메이저맵",
    "description": "메이저맵은 데이터기반 입시/진로서비스를 제공하는 기업으로 국내 140여 개 주요 대학 학과와 커리큘럼 텍스트를 인공지능으로 분석해 학과간 유사도를 도출, 지도 형태로 시각화해 진로 및 학과 탐색, 입시 전략 계획에 도움을 주는 서비스를 운영합니다.",
    "category": "에듀테크 (기타 교육지원 서비스업)",
    "totalInvestment": "비공개",
    "revenue": "10.5억",
    "employees": "16명",
    "investmentStage": "-",
    "investors": "탭엔젤파트너스,에스오에스벤처스",
    "userInvestment": "userId16",
    "myCompanySelectedCount": 345
  }
];